swagger: '2.0'
info:
  version: 1.0.0
  title: swift-blog
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  '/Posts/{id}':
    get:
      tags:
        - Post
      summary: 'Find a model instance by {{id}}'
      operationId: Post.findOne
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Post'
      deprecated: false
    put:
      tags:
        - Post
      summary: Put attributes for a model instance and persist it
      operationId: Post.replace
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Post'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Post'
      deprecated: false
    patch:
      tags:
        - Post
      summary: Patch attributes for a model instance and persist it
      operationId: Post.update
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Post'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Post'
      deprecated: false
    delete:
      tags:
        - Post
      summary: 'Delete a model instance by {{id}}'
      operationId: Post.delete
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
  /Posts:
    post:
      tags:
        - Post
      summary: Create a new instance of the model and persist it
      operationId: Post.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Post'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Post'
      deprecated: false
    get:
      tags:
        - Post
      summary: Find all instances of the model
      operationId: Post.findAll
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
      deprecated: false
    delete:
      tags:
        - Post
      summary: Delete all instances of the model
      operationId: Post.deleteAll
      responses:
        '200':
          description: Request was successful
      deprecated: false
  '/Users/{id}':
    get:
      tags:
        - User
      summary: 'Find a model instance by {{id}}'
      operationId: User.findOne
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/User'
      deprecated: false
    put:
      tags:
        - User
      summary: Put attributes for a model instance and persist it
      operationId: User.replace
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/User'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/User'
      deprecated: false
    patch:
      tags:
        - User
      summary: Patch attributes for a model instance and persist it
      operationId: User.update
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/User'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/User'
      deprecated: false
    delete:
      tags:
        - User
      summary: 'Delete a model instance by {{id}}'
      operationId: User.delete
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
  /Users:
    post:
      tags:
        - User
      summary: Create a new instance of the model and persist it
      operationId: User.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/User'
      deprecated: false
    get:
      tags:
        - User
      summary: Find all instances of the model
      operationId: User.findAll
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      deprecated: false
    delete:
      tags:
        - User
      summary: Delete all instances of the model
      operationId: User.deleteAll
      responses:
        '200':
          description: Request was successful
      deprecated: false
  '/Comments/{id}':
    get:
      tags:
        - Comment
      summary: 'Find a model instance by {{id}}'
      operationId: Comment.findOne
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Comment'
      deprecated: false
    put:
      tags:
        - Comment
      summary: Put attributes for a model instance and persist it
      operationId: Comment.replace
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Comment'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Comment'
      deprecated: false
    patch:
      tags:
        - Comment
      summary: Patch attributes for a model instance and persist it
      operationId: Comment.update
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Comment'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Comment'
      deprecated: false
    delete:
      tags:
        - Comment
      summary: 'Delete a model instance by {{id}}'
      operationId: Comment.delete
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
  /Comments:
    post:
      tags:
        - Comment
      summary: Create a new instance of the model and persist it
      operationId: Comment.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Comment'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Comment'
      deprecated: false
    get:
      tags:
        - Comment
      summary: Find all instances of the model
      operationId: Comment.findAll
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
      deprecated: false
    delete:
      tags:
        - Comment
      summary: Delete all instances of the model
      operationId: Comment.deleteAll
      responses:
        '200':
          description: Request was successful
      deprecated: false
definitions:
  Post:
    properties:
      id:
        type: string
      title:
        type: string
      body:
        type: string
    additionalProperties: false
    required:
      - title
      - body
  User:
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
    additionalProperties: false
    required:
      - name
      - email
  Comment:
    properties:
      id:
        type: string
      body:
        type: string
    additionalProperties: false
    required:
      - body
