container-name-run : "swiftblog-swift-run"
container-name-tools : "swiftblog-swift-tools"
image-name-run : "swiftblog-swiftrun"
image-name-tools: "swiftblog-swifttools"
dockerfile-tools: "Dockerfile-tools"
dockerfile-run: "Dockerfile"
build-cmd-debug : "/root/utils/tools-utils.sh build debug"
debug-cmd : "/root/utils/tools-utils.sh debug swift-blog 1024"
build-cmd-run : "/root/utils/tools-utils.sh build release"
run-cmd : "/root/utils/run-utils.sh run swift-blog"
test-cmd : "/root/utils/tools-utils.sh test"
container-path-run : "/root/project"
container-path-tools : "/root/project"
container-port-map : "8080:8080"
container-port-map-debug : "1024:1024"
